---
global:
  storageClass: standard
  postgresql:
    auth:
      username: worker
      database: app
      existingSecret: "postgres-secret"
      secretKeys:
        adminPasswordKey: "POSTGRES_PASSWORD"
        userPasswordKey: "USER_PASSWORD"
        replicationPasswordKey: "POSTGRES_PASSWORD"
primary:
  name: primary
  pgHbaConfiguration: |-
    local all all  md5
    host  all all 172.20.0.0/16 md5
  networkPolicy:
    allowExternal: false
    extraIngress:
      - ports:
          - port: 5432
        from:
          - podSelector:
              matchLabels:
                app: backend
  persistence:
    enabled: true
    storageClass: standard
    accessModes:
      - ReadWriteOnce
    size: 2Gi
    
    