replicaCount: 1

image:
  repository: nzaitseva/kuber
  tag: latest
  pullPolicy: Always

service:
  enabled: true
  name: frontend-service
  type: ClusterIP
  port: 3000
  targetPort: 3000
pod:
  name: frontend

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "256Mi"
    cpu: "250m"

namespace:
  name: workshop2024

ingress:
  port: 80
  name: nginx-ingress
  
  