apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.service.name }}
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ .Values.pod.name }}
  ports:
    - protocol: TCP
      port: {{ .Values.ingress.port }}
      targetPort: frontend-port
      
      
