- name: Install required packages
  apt:
    name:
      - build-essential
      - zlib1g-dev
      - libncurses5-dev
      - libpq-dev
      - libgdbm-dev
      - libnss3-dev
      - libssl-dev
      - libreadline-dev
      - libffi-dev
      - libsqlite3-dev
      - wget
      - libbz2-dev
    state: present
    update_cache: yes
   
- name: Check if python3.8 is installed
  command: python3.8 --version
  register: python_check
  ignore_errors: yes
 
- name: Download python archive
  get_url:
    url: https://www.python.org/ftp/python/3.8.6/Python-3.8.6.tgz
    dest: /tmp/Python-3.8.6.tgz
  when: python_check.rc != 0

- name: Unpacking python archive
  unarchive:
    src: /tmp/Python-3.8.6.tgz
    dest: /opt/
    remote_src: yes
  when: python_check.rc != 0

- name: Configure python
  shell: ./configure --enable-optimizations
  args:
    chdir: /opt/Python-3.8.6/
  when: python_check.rc != 0

- name: Installation python
  shell: make -j 4 && sudo make altinstall
  args:
    chdir: /opt/Python-3.8.6/
  when: python_check.rc != 0

- name: Install python3-pip
  apt:
    name: python3-pip
    state: present

- name: Install python3-venv
  apt:
    name: python3-venv
    state: present



