apiVersion: v1
kind: ConfigMap
metadata:
  name: postgres-config
data:
  POSTGRES_DB: "app"
  pg_hba.conf: |
    # TYPE  DATABASE        USER            ADDRESS                                                     METHOD
    host    all             all             backend-service.workshop2024.svc.cluster.local               md5
    
