include:
  - project: 'simbirsoft1/devops-workshop-2024-12/natalia.zaitseva/exercise-011/deploy-app'
    file:
    - 'autodevops-template.yml'
  
.tags_anchor: &tags_anchor
    tags:
        - frontend

variables:
  APP_HELM_CHART: '.deploy/helm/frontend'
  DOCKER_HUB_IMAGE: 'nzaitseva/frontend'


Hadolint:
  <<: *tags_anchor

Build:
  <<: *tags_anchor

Deploy:
  <<: *tags_anchor
  
# check