# -*- mode: ruby -*-
# vi: set ft=ruby :

ENV['VAGRANT_SERVER_URL'] = 'https://vagrant.elab.pro'
Vagrant.configure("2") do |config|
  config.vm.network "private_network", ip: "192.168.56.4"
  config.vm.box = "ubuntu/jammy64"
  config.vm.hostname = "testxmachine"  
  config.vm.provision "file", source: "/home/nata/deploy_exercise_04.sh", destination: "/home/vagrant/deploy_exercise_04.sh"
  config.vm.provision "shell", path: "/home/nata/deploy_exercise_04.sh", privileged: false
 
 
  config.vm.provider "virtualbox" do |vb|
     vb.memory = "1024"
     vb.cpus = 2
  end
end



