replicaCount: 1

image:
  repository: nzaitseva/backend
  tag: latest
  pullPolicy: Always

service:
  enabled: true
  name: backend-service
  type: ClusterIP
  port: 8081
  targetPort: 8081
pod:
  name: backend

resources:
  requests:
    memory: "256Mi"
    cpu: "250m"
  limits:
    memory: "256Mi"
    cpu: "250m"

env:
- name: POSTGRES_SERVER_HOST
  valueFrom:
    configMapKeyRef:
      name: backend-config
      key: POSTGRES_SERVER_HOST
- name: POSTGRES_USER
  valueFrom:
    configMapKeyRef:
      name: backend-config
      key: POSTGRES_USER
- name: POSTGRES_PASSWORD
  valueFrom:
    secretKeyRef:
      name: backend-secret
      key: POSTGRES_PASSWORD
- name: POSTGRES_DB
  valueFrom:
    configMapKeyRef:
      name: backend-config
      key: POSTGRES_DB
- name: CLIENT_URL
  valueFrom:
    configMapKeyRef:
      name: backend-config
      key: CLIENT_URL
- name: SERVER_PORT
  valueFrom:
    configMapKeyRef:
      name: backend-config
      key: SERVER_PORT
- name: JWT_KEY
  valueFrom:
    secretKeyRef:
      name: backend-secret
      key: JWT_KEY
- name: RUN_MIGRATION
  valueFrom:
    configMapKeyRef:
      name: backend-config
      key: RUN_MIGRATION
      